# Generated by Django 3.0.3 on 2020-02-19 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("osusu_system", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="partclaim",
            name="part",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="osusu_system.Part",
                verbose_name="Part",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="claim",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("approved", "Approved"),
                    ("approved_paid", "Approved & Paid"),
                    ("rejected", "Rejected"),
                ],
                default="open",
                max_length=50,
            ),
        ),
    ]
