# Generated by Django 3.0.3 on 2020-02-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("osusu_system", "0002_auto_20200219_1347")]

    operations = [
        migrations.RemoveField(model_name="part", name="amount"),
        migrations.AddField(
            model_name="part",
            name="value",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=100,
                verbose_name="Part Value (SLL)",
            ),
            preserve_default=False,
        ),
    ]
