# Generated by Django 3.0.3 on 2020-02-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("osusu_system", "0003_auto_20200219_1458")]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="status",
            field=models.CharField(
                choices=[
                    ("Open", "Open"),
                    ("Approved", "Approved"),
                    ("Approved & Paid", "Approved & Paid"),
                    ("Rejected", "Rejected"),
                ],
                default="open",
                max_length=50,
            ),
        )
    ]
