# Generated by Django 3.0.3 on 2020-03-04 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("osusu_system", "0007_auto_20200226_1521")]

    operations = [
        migrations.AlterModelOptions(name="payment", options={"ordering": ("-date",)})
    ]
