# Generated by Django 3.0.3 on 2020-03-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("osusu_system", "0008_auto_20200304_1648")]

    operations = [
        migrations.AddField(
            model_name="partclaim",
            name="value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        )
    ]
