# Generated by Django 3.0.3 on 2020-03-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("osusu_system", "0009_partclaim_value")]

    operations = [
        migrations.AlterField(
            model_name="partclaim",
            name="value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=100, null=True
            ),
        )
    ]
